config/routes.rb
PJTracker::Application.routes.draw do

   resources :projects do
      resources :tasks #, :except => [:show, :index]
      member do
        put 'user_add'
        post 'update_desc'
      end
        
    end

  devise_for :users
  resource :home

  root :to => 'home#index'

  
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tasks
  validates :deadline, :presence => true , :format => { :with => /^(([1][012])||[0][1-9])\/(([0][1-9])||([12][0-9])||([3][0-2]))\/([2][0-9][1-9][0-9])$/}
  validates :name, :presence => true ,:length => {:minimum => 6},:format => {:with =>/^(\w|\s|[-]|['])*$/i}
  validates :description, :presence => true 
end

app/models/projects_users.rb
class ProjectsUsers < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  attr_accessible :name, :description
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  has_and_belongs_to_many :projects
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base

  layout 'main'

  def index
  if user_signed_in?
  @allprojects = Project.all
  @myprojects = current_user.projects
  respond_to do |format|
  format.html
  end
  else
    redirect_to user_session_path
  end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  before_filter :authenticate_user!

  def index
    #@projects = Project.all
    @projects = Project.paginate(:page => params[:page], :per_page => 3)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    if @project.author == current_user.id
      @project = Project.find(params[:id])
    else
      flash[:alert] = 'You do not have permission to access this page !'
      redirect_to projects_path
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.author = current_user
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: "new"
    end

  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    if @project.author == current_user.id
      @project.destroy
    else
      flash[:alert] = 'You do not have permission to access this page !'
      redirect_to projects_path
    end    
  end

  # POST /projects/1/add_user
  def user_add
    @project = Project.find(params[:id])
    if @project.author == current_user.id 
    @usr = User.find(params[:post]['user'])
    if @project.users.where(:id => @usr.id).exists? 
      respond_to do |format|
        format.html { redirect_to @project, notice: 'Opps ! This User is already assigned to your project.' }
      end
    else
      @project.users << @usr
      respond_to do |format|
        format.html { redirect_to @project, notice: '1 user added to your project.' }
      end
    end
    else
         flash[:alert] = 'You do not have permission to access this page !'
         redirect_to project_path('You do not have permission to perform this operation !')
    end
  end

  def update_desc
    @project = Project.find(params[:id])
    @project.description =params[:value]
    if @project.save
      respond_to do |format|
      format.js
      end
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ActionController::Base

  layout 'main'
  before_filter :authenticate_user!,:find_project

  def create
    if @project.author == current_user.id
    @task = @project.tasks.build(params[:task])
    @task.user_id = params[:task]['user_id']
    @task.save

    respond_to do |format|
      format.html {redirect_to project_path(@project)}
      format.js
    end
  else
    flash[:alert] = 'You do not have permission to perform this action !'
    redirect_to project_path(@project)
  end
  end

  def find_project
    @project = Project.find(params[:project_id])
    @usr = find(params[:add])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<table class="list-box">
<tr><td><%=render 'shared/project_block' %></td>
<td><%=render 'shared/task_block' %></td>
<td><%=render 'shared/project_owned' %></td></tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

<%= javascript_include_tag "application" %>

<%= stylesheet_link_tag "main" , "jquery-ui"%>

<%= csrf_meta_tag %>

</head>
<body>
<div id="container">
<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%=render 'shared/header' %>
<%= yield %>
</div>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
<%= javascript_include_tag "jquery", "jquery_ui" %>
<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag "jquery-ui" ,"main" %>
<%= csrf_meta_tag %>

</head>
<body>
<div id="container">
<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%=render 'shared/header' %>
<%= yield %>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<fieldset>
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,rows: 16,cols: 74 %>
  </p>

  <p class="field">
    <%= f.label :deadline %><br />
    <%= f.text_field :deadline ,placeholder: "pick date" %>
  </p>
  <% if @project.id!=nil %>
  <p class="field">
    <%= f.label :status %><br />
     <%= select_tag('project[status]',options_for_select( [ ['Analysis','Analysis' ], ['Design','Design' ], ['Code', 'Code'], ['Test', 'Test'], ['Completed', 'Completed'],['Delivered', 'Delivered'] ])) %>
  </p>
  <% end %>
  <% if @project.id==nil %>
  <p class="users">
    <b>Assign Users </b><br/>
    <% User.all.each do |u| %>

    <%= check_box_tag 'project[user_ids][]', u.id -%>
    <label><span><%=  u.email -%></span></label>

    <% end %>
  </p>
<%end%>
  <p class="actions">
    <%= f.submit %>
  </p>
  <% end %>
</fieldset>

app/views/projects/edit.html.erb
<h2>Editing project</h2>

<%= render 'form' %>

<br />

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h2>Listing projects</h2>

<table>
  <tr>
    <th>Name of The Project</th>
    <th>Created At</th>
    <th>Author</th>
    <th>Deadline</th>
    <th>Status</th>
    <th colspan="3">Actions</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%=project.created_at %></td>
    <td><%=(User.find(project.author)).email%></td>
    <td><%= project.deadline %></td>
    <td><%=project.status %></td>
    <td><%= link_to 'Show', project %></td>
    <% if project.author == current_user.id %>
    <td id="edit_<%=(project.id) %>"><%= link_to 'Edit', edit_project_path(project) %></td>
    <td id="destroy_<%=(project.id) %>"><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>

    <% end %>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @projects %>
<br />
<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render 'form' %>

<br />

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>
<p>
  <b>Author:</b>
  <%= User.find(@project.author).email %>
</p>
<p>
  <b>Description:</b><br />
  <%= best_in_place @project, :description, :type => :textarea %>
   
</p>
<p>
  <b>Status:</b>
  <%= @project.status %>
</p>
<p>
  <p>
    <b>Deadline:</b>
    <%= @project.deadline %>
  </p>
  <p>

    <b>Users:</b>

    <b>Listing Available Collaborators</b>
    <ul class="long">

      <% @project.users.each do |u| %>

      <% @u_tasks = @project.tasks.where(:user_id => u) %>

      <li>
        <% if @u_tasks.empty? %>
        <b><%= u.email %></b>
        <%if @project.author == current_user.id %>
        <span class="assign_task">Assign Tasks:</span>

        <div class="tasks">
          <p>Enter Task Details</p>
          <%= form_for [@project, Task.new], :html => { :id => "project_user_#{u.id}" } do |f| %>
          <input type="hidden" value="<%=u.id%>" name="task[user_id]" />

          <p class="fleld"><%= f.label :name %><br />
            <%= f.text_field :name %></p>
            <p class="field">
              <%= f.label :description %><br />
             <%= f.text_area :description,rows: 4,cols: 44 %>
            </p>
            <p class="actions">
              <%= f.submit %>
            </p>

            <% end %>
          </div>
          <%end%>
          <% else %>
          <% @u_tasks.each do |u_wid_task| %>
          <span>   &#9786;   <%=u.email%></span><div class="task-list">
            <b>Assigned Task</b><br/>
            <u>Name: </u><%=u_wid_task.name%><br />
            <u>Description:</u> 
           
            <%=u_wid_task.description%>
           
          </div>
          <%end%>
          <% end %>
        </li>

        <% end %>

      </ul>
    </p>
      
      <%if @project.author == current_user.id %>
      <p>  
       <%= form_for @project,:url => { :action => "user_add" } do |f| %>
      <b>Add More Collaborators </b>
      <select name="post[user]">
      <% User.all.each do |u|
      if not @project.users.where(:id => u.id).exists? 
      %>
      <%=options_for_select([[u.email, u.id]])%>
      <%
      end
      end
      %>
      </select>
      <%=submit_tag "Add"%>
      <%end%>
      </p>
      <%end%>

      <%= link_to 'Edit', edit_project_path(@project) %> |
      <%= link_to 'Back', projects_path %>

app/views/projects/update_desc.js.erb
<%=@project.description %>

app/views/shared/_header.html.erb
<h1>The Project Tracker Rails App</h1>
<div class="user-info">
<% if user_signed_in? %>
Welcome <b> <%=current_user.email %> </b> | <%= link_to "Log Out",destroy_user_session_path, :method=>:delete %>
<% end  %>
</div>
<% if user_signed_in? %>
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'New Project', new_project_path %></li>
    <li><%= link_to 'All Projects', projects_path %></li>
  </ul>
 </nav>
 <% end %>
 <div class="clear"></div>

app/views/shared/_project_block.html.erb
<div class="box-block">
<header>My Projects</header>
<% @myprojects.each do |p| %>
<div>
<p><b>Project: </b><%=p.name%></p>
<p><b>Created By: </b><%=User.find(p.author).email%></p>
<p><b>Status: </b><%=p.status%></p>
<p><b>Deadline: </b><%=p.deadline%></p>
<%=link_to 'read more',p %>
</div>
<% end %>
</div>

app/views/shared/_project_owned.html.erb
<div class="box-block">
<header>Authored Projects</header>
<% myprojects = Project.where(:author => current_user.id) %>
<% myprojects.each do |p| %>
<div>
<p><b>Project: </b><%=p.name%></p>
<p><b>Status: </b><%=p.status%></p>
<p><b>Collaborators: </b>
<% users = p.users %>
<% users.each do |u| %>
<p>&#8857; <%=u.email%> <%="[ Myself ]" if u == current_user%></p>
<%end%>
</p>
<%=link_to 'read more',p %>
</div>
<% end %>
</div>

app/views/shared/_task_block.html.erb
<div class="box-block">
<header>My Tasks</header>
<% mytasks = current_user.tasks %>
<% mytasks.each do |t| %>
<div>
<p><b>Task Name: </b><%=t.name%></p>
<p><b>For Project: </b><%=t.project.name%></p>
</div>
<% end %>
</div>